# Generated by Django 4.1.7 on 2023-03-12 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isDoctor",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "MALE"), ("FEMALE", "FEMALE")], max_length=255
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A Positive", "A Positive"),
                            ("A Negative", "A Negative"),
                            ("B Positive", "B Positive"),
                            ("B Negative", "B Negative"),
                            ("O Positive", "O Positive"),
                            ("O Negative", "O Negative"),
                            ("AB Positive", "AB Positive"),
                            ("AB Negative", "AB Negative"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("height", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience", models.IntegerField()),
                ("cost", models.IntegerField()),
                ("about", models.TextField()),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("General Health", "General Health"),
                            ("Pediatrician", "Pediatrician"),
                            ("Dentist", "Dentist"),
                            ("Orthopedist", "Orthopedist"),
                            ("Dermatologist", "Dermatologist"),
                        ],
                        max_length=255,
                    ),
                ),
                ("address", models.CharField(max_length=511)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Chennai", "Chennai"),
                            ("Delhi", "Delhi"),
                            ("Mumbai", "Mumbai"),
                            ("Kolkata", "Kolkata"),
                            ("Hydrabad", "Hydrabad"),
                            ("Banglore", "Banglore"),
                        ],
                        max_length=255,
                    ),
                ),
                ("degrees", models.CharField(max_length=511)),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookSlots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booked_at", models.DateTimeField(auto_now=True, null=True)),
                ("booking_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "doctorProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_profile",
                        to="profiles.doctorprofile",
                    ),
                ),
                (
                    "patientProfile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_profile",
                        to="profiles.patientprofile",
                    ),
                ),
            ],
        ),
    ]
