# Generated by Django 4.1.7 on 2023-03-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_user_isdoctor_alter_user_email_patientprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=255
            ),
        ),
    ]
