# Generated by Django 4.1.7 on 2023-03-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_rename_birth_date_patientprofile_birthdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookslots",
            name="cost",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
