# Generated by Django 4.1.7 on 2023-03-16 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_remove_bookslots_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookslots",
            name="patientProfile",
            field=models.ForeignKey(
                blank=True,
                default=-1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient_profile",
                to="profiles.patientprofile",
            ),
        ),
    ]
