# Generated by Django 4.1.7 on 2023-03-17 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_patientmedicalimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientmedicalimage",
            old_name="patient_profile",
            new_name="patientProfile",
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctorProfile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patientProfile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
