# Generated by Django 4.1.7 on 2023-03-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0010_rename_patient_profile_patientmedicalimage_patientprofile_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientmedicalimage",
            name="patientProfile",
        ),
    ]
