# Generated by Django 4.1.7 on 2023-03-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_remove_patientmedicalimage_patientprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientmedicalimage",
            name="patientProfile",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="profiles.patientprofile",
            ),
            preserve_default=False,
        ),
    ]
