# Generated by Django 4.1.7 on 2023-03-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_patientmedicalimage_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientmedicalimage",
            name="key",
            field=models.CharField(max_length=1024),
        ),
    ]
